### ISSUE TITLE
[Bug]:  OIAA Meeting Guide is down

### ISSUE THREAD

**Issue by melindafries** [code4recovery/central#14]
### Contact Details

web.services@aa-intergroup.org

### Website With Issue

https://aa-intergroup.org/meetings/

### What happened?

OIAA Meeting Guide is down. It is displaying this error:
SyntaxError: Unexpected non-whitespace character after JSON at position 6673480 (line 1 column 6673481)

### What browsers are you seeing the problem on?

Chrome

**Comment by melindafries** [comment]
Got it on where to submit and I'll put that in our documentation.
That's amazing it's only happened once. I'll let Matt know what's up when he awakens.

**Comment by joshreisner** [comment]
as to the question of _why_ did this happen, which as i note above hasn't happened before (but I guess we launched in June so it's only been ~6 months) i think what may have happened were there were a few meetings archived all at the same time (nothing wrong with that per se) and so we wrote the JSON file to Dean's server five times - sucesssively shorter versions each time

<img width="1325" alt="Screenshot 2023-12-29 at 8 40 49 AM" src="https://github.com/code4recovery/central/assets/1551689/0515c429-8e7f-4829-a266-b601c75a5191">

writing the JSON file is an async process, so i think what may have happened was one write may have been already pending when the next write came in, and somehow they must have overlapped to create the error above. if it happens again, waiting a few (maybe 15 or more) seconds and triggering another write by making an edit to a meeting _should_ fix it hopefully

i've created a new feature request issue #15 to be able to archive a whole group in one go which might also help or at least be a convenience, but in the meantime we don't need to avoid manually archiving each meeting in a group)

also there's a group within code for recovery that is working on a JSON-less approach which would eliminate this as a potential problem in the future
