### ISSUE TITLE
Inconsistent Search Results

### ISSUE THREAD

**Issue by mattbylett** [code4recovery/central#17]
The 2 search engines in central and the frontend meeting guide are giving different results.

The meeting is "What's good about today"  - OIMN 49195.  Playing about with different combinations in the search bars returns very different results..

- "Whats" in Central returns the desired result, however "What's.. " is required in the meeting guide
- "What's" in central returns no meetings found
- "Whats good about today" is searchable in central but "What's good about today" returns no results in the meeting guide

etc

Any ideas?

many thanks in advance

Matt

**Comment by joshreisner** [comment]
looks like in both cases the issue is that your meeting has a curly quote `What’s` and when you search with a straight quote `What's` you get no results

we [already have a ticket](https://github.com/code4recovery/central/issues/11) about search results in central, so i will add this to that
