### ISSUE TITLE
Live TEAMS support

### ISSUE THREAD

**Issue by twn2twn** [code4recovery/central#21]
Hi this is Jeff B OIAA, 

Can the Teams platform be added?

We have this meeting listed
https://aa-intergroup.org/meetings/tuesday-daily-reflections-1hr-meeting-uk/

thank you, Jeff B

**Comment by joshreisner** [comment]
hi @twn2twn i've added teams support now to central, and [added it to online meeting list](https://github.com/code4recovery/online-meeting-list/compare/ac49e735c2a0...12ab4f03b6f4) as well

@mattbylett when you get a chance if you could rebuild for the site, thanks

**Comment by twn2twn** [comment]
Thank you both!

**Comment by twn2twn** [comment]
Hi again, Before you close this out, is it possible to add another platform filter "Virtual Reality"?
Allows these two meeting types to be categorized under VR?

https://aa-intergroup.org/meetings/?search=aainvr

https://aa-intergroup.org/meetings/recovery-journey-7/

thank you, Jeff B
