### ISSUE TITLE
Hi again, Before you close this out, is it possible to add another platform filter "Virtual Reality"?

### ISSUE THREAD

**Issue by joshreisner** [code4recovery/central#22]
Hi again, Before you close this out, is it possible to add another platform filter "Virtual Reality"?
Allows these two meeting types to be categorized under VR?

https://aa-intergroup.org/meetings/?search=aainvr

https://aa-intergroup.org/meetings/recovery-journey-7/

thank you, Jeff B

_Originally posted by @twn2twn in https://github.com/code4recovery/central/issues/21#issuecomment-2395753706_

**Comment by joshreisner** [comment]
interesting - looks like there are 24 meetings in Second Life (some of these are pretty old i think) and two new ones in Meta Horizons. 

i'm not sure "virtual reality" is the right descriptor here - Second Life is not really defined as VR (it's just 3d). also they're not really related formats - someone who is looking for one is not likely to consider the other format an alternative

but i think we could add them separately - the way we do this by validating a URL pattern to join the meeting. looks like the Meta Horizons URLs start with `https://horizon.meta.com/world/` and the [Second Life URLs start with](https://wiki.secondlife.com/wiki/Linden_Lab_Official:Map_API_SLurl_Technical_Details) either `http://maps.secondlife.com/secondlife/` or `http://slurl.com/secondlife/`. most of these meetings already have URLs with this pattern in their meeting descriptions. the exception is the [Friends of Bill W](https://central.aa-intergroup.org/groups/648e6e3db291ed6c51361413) meeting. looks like this description needs to be updated anyway since it says there are seven weekly meetings but only six are listed

lmk if you want us to proceed?

**Comment by twn2twn** [comment]
Hi Josh, Yes, please go forward with this. 
I'm trying to contact the Friends of Bill W group now to see if they're going to be in the mix and see if I can get a link. 
thank you, Jeff B

**Comment by joshreisner** [comment]
ok i've added these urls patterns to central, and to online meeting list. i guess i forgot that second life was already in there, so if you set those now they will show up. for meta horizon meetings to show up in the filters we'll need another deploy from @mattbylett 

incidentally i improved several other things as well:
* the meeting list no longer overflows to the right on mobile sometimes
* listings inside the group accordion look better now
* you can enable "edit links" to jump you from a meeting listing on the public site right into central by opening your browser javascript console and entering `localStorage.setItem('admin', true)`

**Comment by twn2twn** [comment]
Thank you, sir. I appreciate this!

**Comment by mattbylett** [comment]
Morning chaps - I've rebuilt and deployed this but not sure it's worked
please check and confirm if its correct

I tested by setting admin to true but can't see "edit links"

am I missing something obvious?

**Comment by mattbylett** [comment]
Sorry my bad - all is well - I uploaded the wrong build - have now rectified

**Comment by joshreisner** [comment]
great, thanks!

the edit links look like this:
<img width="608" alt="Screenshot 2024-10-09 at 10 07 30 AM" src="https://github.com/user-attachments/assets/63b594f4-7953-473a-89bb-227139eb22dc">

**Comment by mattbylett** [comment]
:) yeah all good - I see them now - Between you and me - I didn't git pull
before I built 🫣 - its early here 😆

All sorted now

Thanks for all your hard work :)
