### ISSUE TITLE
Adding "VRChat" to types of meetings

### ISSUE THREAD

**Issue by twn2twn** [code4recovery/central#25]
Hi, Jeff B - OIAA, 

I'm getting requests to add VRChat to meeting types (ASL, RSL, Deaf, etc). 

This is for meeting such as Second Life and whatever else falls into this category now or in the future. 
thank you, Jeff B

**Comment by joshreisner** [comment]
we added Second Life and Meta Horizon as formats, i don't see the need for an additional meeting type for this. if they want to they should make the case for what this type would mean for users and why it would help people find a meeting in a way that the formats do not
